# Generated by Django 5.2.4 on 2025-07-17 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(max_length=100)),
                ('oem', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('shelf', models.CharField(max_length=10)),
                ('level', models.CharField(max_length=10)),
                ('row', models.CharField(max_length=10)),
            ],
        ),
    ]
