# Generated by Django 5.2.4 on 2025-07-17 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='level',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='part',
            name='row',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='part',
            name='shelf',
            field=models.CharField(max_length=20),
        ),
    ]
