# Generated by Django 5.2.4 on 2025-07-21 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0002_alter_part_level_alter_part_row_alter_part_shelf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='part',
            old_name='row',
            new_name='row_position',
        ),
    ]
